In [1]:
import numpy as np
import pandas as pd
from tabulate import tabulate

# Gr√°ficos
# ==============================================================================
import matplotlib.pyplot as plt
from matplotlib import style
import matplotlib.ticker as ticker
import seaborn as sns

# Preprocesado y modelado
# ==============================================================================
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RepeatedKFold
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import make_blobs
from sklearn.metrics import euclidean_distances
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import Ridge
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor

from skopt.space import Real, Integer
from skopt.utils import use_named_args
from skopt import gp_minimize
from skopt.plots import plot_convergence

# Varios
# ==============================================================================
import multiprocessing
import random
from itertools import product
from fitter import Fitter, get_common_distributions

In [2]:
diamonds_train = pd.read_csv('db/diamonds_train.csv')
diamonds_test = pd.read_csv('db/diamonds_test.csv')

In [3]:
print("Cut: ",set(diamonds_train["cut"]))
print("Color: ",set(diamonds_train["color"]))
print("Clarity: ",set(diamonds_train["clarity"]))

Cut:  {'Good', 'Ideal', 'Fair', 'Premium', 'Very Good'}
Color:  {'I', 'G', 'H', 'F', 'D', 'E', 'J'}
Clarity:  {'SI1', 'IF', 'SI2', 'VS1', 'VVS1', 'VS2', 'I1', 'VVS2'}

In [4]:
diamonds_train['price/wt']=diamonds_train['price']/diamonds_train['carat']
print(diamonds_train.groupby('cut')['price/wt'].mean().sort_values())
print(diamonds_train.groupby('color')['price/wt'].mean().sort_values())
print(diamonds_train.groupby('clarity')['price/wt'].mean().sort_values())
diamonds_train = diamonds_train.drop(['price/wt','table'], axis=1)

cut
Fair         3757.492344
Good         3832.597411
Ideal        3908.044496
Very Good    4014.378029
Premium      4231.131397
Name: price/wt, dtype: float64
color
E    3810.101878
J    3827.670485
D    3937.805478
I    3980.836098
H    4006.343705
F    4106.324111
G    4171.555393
Name: price/wt, dtype: float64
clarity
I1      2798.055592
SI1     3844.657269
VVS1    3882.807337
SI2     4025.614743
VS2     4074.905291
VS1     4129.189881
VVS2    4178.017868
IF      4217.324475
Name: price/wt, dtype: float64

In [5]:
diamonds_train['cut']=diamonds_train['cut'].map({'Ideal':5,'Good':2,'Very Good':3,'Fair':1,'Premium':4})
diamonds_train['color']=diamonds_train['color'].map({'E':2,'D':1,'F':3,'G':4,'H':5,'I':6,'J':7})
diamonds_train['clarity']=diamonds_train['clarity'].map({'VVS1':7,'IF':8,'VVS2':6,'VS1':5,'I1':1,'VS2':4,'SI1':3,'SI2':2})

In [6]:
diamonds_train.corr()

,carat,cut,color,clarity,depth,price,x,y,z
carat,1.000000,-0.136154,0.294027,-0.357279,0.026528,0.921935,0.975688,0.951667,0.967570
cut,-0.136154,1.000000,-0.024355,0.192034,-0.226255,-0.053800,-0.126509,-0.122351,-0.152732
color,0.294027,-0.024355,1.000000,0.020750,0.047988,0.174855,0.272498,0.265611,0.275022
clarity,-0.357279,0.192034,0.020750,1.000000,-0.071775,-0.151893,-0.375764,-0.362133,-0.376815
depth,0.026528,-0.226255,0.047988,-0.071775,1.000000,-0.014864,-0.026348,-0.030966,0.094655
price,0.921935,-0.053800,0.174855,-0.151893,-0.014864,1.000000,0.885848,0.866163,0.874500
x,0.975688,-0.126509,0.272498,-0.375764,-0.026348,0.885848,1.000000,0.973712,0.984876
y,0.951667,-0.122351,0.265611,-0.362133,-0.030966,0.866163,0.973712,1.000000,0.964828
z,0.967570,-0.152732,0.275022,-0.376815,0.094655,0.874500,0.984876,0.964828,1.000000

In [7]:
diamonds_train['cut/wt']=diamonds_train['cut']/diamonds_train['carat']
diamonds_train['color/wt']=diamonds_train['color']/diamonds_train['carat']
diamonds_train['clarity/wt']=diamonds_train['clarity']/diamonds_train['carat']
diamonds_train = diamonds_train.drop(['cut','color','clarity','depth','city','x','y','z'], axis=1)

In [8]:
diamonds_train

       carat  price     cut/wt   color/wt  clarity/wt
0       1.21   4268   3.305785   5.785124    3.305785
1       1.02   3513   3.921569   6.862745    3.921569
2       0.77   1792   5.194805   9.090909    5.194805
3       1.51   7553   2.649007   4.635762    2.649007
4       0.57   1176   7.017544  12.280702    7.017544
...      ...    ...        ...        ...         ...
40450   0.54   2729   9.259259   5.555556   14.814815
40451   0.53   2802   9.433962   5.660377   15.094340
40452   0.30    886  16.666667  10.000000   26.666667
40453   0.26    768  19.230769  11.538462   30.769231
40454   0.31    921  16.129032   9.677419   25.806452

[40455 rows x 5 columns]

In [9]:
#from sklearn.preprocessing import MinMaxScaler
#scaler = MinMaxScaler()
#features = ['carat','cut/wt','color/wt','clarity/wt']
#diamonds_scaled = scaler.fit_transform(diamonds_train.loc[:,features].values)
#diamond_scaler_df = pd.DataFrame(diamonds_scaled, columns=["carat",'cut/wt','color/wt','clarity/wt'])

In [10]:
X=diamonds_train.drop(['price'],axis=1)
Y=diamonds_train['price']
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_regression
#X, Y = make_regression(n_samples=1000, n_features=4, random_state=42)
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.15,random_state=42)
#print(X.shape, Y.shape)

In [11]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state = 0)
regressor.fit(X_train, Y_train)
y_pred = regressor.predict(X_test)

In [12]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
mae = mean_absolute_error(Y_test,y_pred)
print("mae: %f" %(mae))
Rsquare=regressor.score(X_test,Y_test)
print("Rsquare: %f" %(Rsquare))
rmse=np.sqrt(mean_squared_error(Y_test,y_pred))
print("rmse: %f" %(rmse))

mae: 327.621938
Rsquare: 0.973567
rmse: 663.460809

In [13]:
diamonds_test

,id,carat,cut,color,clarity,depth,table,x,y,z,city
0,0,0.79,Very Good,F,SI1,62.7,60.0,5.82,5.89,3.67,Amsterdam
1,1,1.20,Ideal,J,VS1,61.0,57.0,6.81,6.89,4.18,Surat
2,2,1.57,Premium,H,SI1,62.2,61.0,7.38,7.32,4.57,Kimberly
3,3,0.90,Very Good,F,SI1,63.8,54.0,6.09,6.13,3.90,Kimberly
4,4,0.50,Very Good,F,VS1,62.9,58.0,5.05,5.09,3.19,Amsterdam
...,...,...,...,...,...,...,...,...,...,...,...
13480,13480,0.57,Ideal,E,SI1,61.9,56.0,5.35,5.32,3.30,Amsterdam
13481,13481,0.71,Ideal,I,VS2,62.2,55.0,5.71,5.73,3.56,New York City
13482,13482,0.70,Ideal,F,VS1,61.6,55.0,5.75,5.71,3.53,Tel Aviv
13483,13483,0.70,Very Good,F,SI2,58.8,57.0,5.85,5.89,3.45,Surat
13484,13484,0.40,Ideal,I,VVS2,62.4,55.0,4.70,4.73,2.94,New York City

In [14]:
diamonds_test['cut']=diamonds_test['cut'].map({'Ideal':5,'Good':2,'Very Good':3,'Fair':1,'Premium':4})
diamonds_test['color']=diamonds_test['color'].map({'E':2,'D':1,'F':3,'G':4,'H':5,'I':6,'J':7})
diamonds_test['clarity']=diamonds_test['clarity'].map({'VVS1':7,'IF':8,'VVS2':6,'VS1':5,'I1':1,'VS2':4,'SI1':3,'SI2':2})

In [15]:
diamonds_test.corr()

,id,carat,cut,color,clarity,depth,table,x,y,z
id,1.000000,-0.002578,-0.005987,-0.016744,-0.000520,-0.002425,0.004891,-0.000102,-0.002206,0.000456
carat,-0.002578,1.000000,-0.131343,0.283612,-0.339339,0.033385,0.176245,0.973283,0.951900,0.913598
cut,-0.005987,-0.131343,1.000000,-0.008975,0.180545,-0.193434,-0.443268,-0.122686,-0.118735,-0.139663
color,-0.016744,0.283612,-0.008975,1.000000,0.040355,0.045076,0.012697,0.263669,0.257501,0.249108
clarity,-0.000520,-0.339339,0.180545,0.040355,1.000000,-0.054188,-0.174281,-0.360598,-0.347121,-0.339044
depth,-0.002425,0.033385,-0.193434,0.045076,-0.054188,1.000000,-0.303653,-0.022049,-0.024359,0.095831
table,0.004891,0.176245,-0.443268,0.012697,-0.174281,-0.303653,1.000000,0.193130,0.180943,0.138777
x,-0.000102,0.973283,-0.122686,0.263669,-0.360598,-0.022049,0.193130,1.000000,0.977762,0.931211
y,-0.002206,0.951900,-0.118735,0.257501,-0.347121,-0.024359,0.180943,0.977762,1.000000,0.916161
z,0.000456,0.913598,-0.139663,0.249108,-0.339044,0.095831,0.138777,0.931211,0.916161,1.000000

In [16]:
diamonds_test['cut/wt']=diamonds_test['cut']/diamonds_test['carat']
diamonds_test['color/wt']=diamonds_test['color']/diamonds_test['carat']
diamonds_test['clarity/wt']=diamonds_test['clarity']/diamonds_test['carat']
diamonds_test = diamonds_test.drop(['cut','color','clarity','table','depth','city','x','y','z'], axis=1)

In [17]:
diamonds_test_x = diamonds_test.drop(['id'],axis=1)

In [18]:
#from sklearn.preprocessing import MinMaxScaler
#scaler = MinMaxScaler()
#features = ['carat','cut/wt','color/wt','clarity/wt']
#diamonds_scaled = scaler.fit_transform(diamonds_test.loc[:,features].values)
#diamonds_test_scaled = scaler.fit_transform(diamonds_test.loc[:,features].values)

In [19]:
from sklearn.tree import DecisionTreeRegressor
model = DecisionTreeRegressor
regressor1 = model(random_state = 42)
regressor1.fit(X, Y)
y_pred1 = regressor1.predict(diamonds_test_x)

In [20]:
y_pred1

array([ 3135.75      ,  5287.        , 10990.        , ...,
        3009.05      ,  2018.81818182,   999.71428571])

In [21]:
#submisions = pd.DataFrame({"id": diamonds_test["id"], "price": y_pred1})

In [22]:
#submisions.to_csv("db/submision3.csv", index=False)

In [23]:
hyperparameters = regressor1.get_params()

print(type(model), '\n')
print('Model hyperparameters:', hyperparameters, '\n')

<class 'abc.ABCMeta'>

Model hyperparameters: {'ccp_alpha': 0.0, 'criterion': 'squared_error', 'max_depth': None, 'max_features': None, 'max_leaf_nodes': None, 'min_impurity_decrease': 0.0, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'random_state': 42, 'splitter': 'best'}

In [24]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(regressor1, 
                         X, 
                         Y, 
                         scoring='neg_root_mean_squared_error', 
                         cv=5,
                         n_jobs=-1)

print(type(model), '\n')
print(scores, '\n')
print(np.mean(-scores), '\n')

<class 'abc.ABCMeta'>

[-673.74245607 -654.89516881 -665.68888179 -692.98076218 -683.29804447]

674.1210626672514

In [25]:
'''X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

#model_rmse = DecisionTreeRegressor(random_state = 42)
#model_rmse = GradientBoostingRegressor(random_state = 42)
model_rmse = RandomForestRegressor(random_state = 42)

model_rmse.fit(X_train, y_train)
y_pred = model_rmse.predict(X_test)

hyperparameters = model_rmse.get_params()

rmse = mean_squared_error(y_test, y_pred)**0.5

print(type(model_rmse), '\n')
print(rmse, '\n')'''

<class 'sklearn.ensemble._forest.RandomForestRegressor'>

582.2381802331646

In [33]:
param_grid = {'n_estimators': [16, 32, 64, 128, 256, 512],
              'max_depth': [2, 4, 8, 16]}

In [34]:
from sklearn.model_selection import RandomizedSearchCV
grid_search = RandomizedSearchCV(model, 
                                 param_grid, 
                                 cv=5, 
                                 verbose=3, 
                                 scoring='neg_root_mean_squared_error', 
                                 n_jobs=-1)

In [35]:
grid_search.fit(X,Y)

#print('\n', 'Best hyperparameters: ', grid_search.best_params_, '\n')
#print('Best score: ', -grid_search.best_score_, '\n')

TypeError: Cannot clone object. You should provide an instance of scikit-learn estimator instead of a class.

array([8494.252     ,  505.37799711, 7386.29166667, ..., 9149.312     ,
       3441.707     , 4653.55998672])